# Generated by Django 5.0.3 on 2024-04-21 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=2048)),
                ("bucket", models.CharField(max_length=255)),
                ("hash", models.CharField(max_length=255)),
                ("size", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=20)),
                ("last_modified", models.DateTimeField()),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="chat.chat",
                    ),
                ),
            ],
        ),
    ]
