# Generated by Django 5.0.3 on 2024-04-21 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storageitem",
            name="last_modified",
        ),
    ]
