# Generated by Django 5.0.3 on 2024-04-29 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0003_alter_storageitem_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storageitem",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="storageitem",
            name="type",
        ),
    ]
