# Generated by Django 5.0.3 on 2024-04-21 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "chat_users",
                    models.ManyToManyField(
                        related_name="user_chats", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatLine",
            fields=[
                ("chat_line_id", models.AutoField(primary_key=True, serialize=False)),
                ("line_text", models.CharField(max_length=2048)),
                ("created_at", models.DateTimeField()),
                ("is_read", models.BooleanField(default=False)),
                ("message_hash", models.CharField(max_length=255)),
                (
                    "chat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="chat.chat",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
