# Generated by Django 5.0.3 on 2024-04-26 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("size", models.IntegerField()),
                ("file_hash", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="chatline",
            name="file",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.file"
            ),
        ),
    ]
