# Generated by Django 5.0.3 on 2024-05-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_file_alter_chatline_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatline",
            old_name="chat_id",
            new_name="chat",
        ),
        migrations.RenameField(
            model_name="chatline",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="file",
            name="file_hash",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.CharField(max_length=20),
        ),
    ]
