# Generated by Django 5.0.3 on 2024-05-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_rename_chat_id_chatline_chat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="preview",
            field=models.BinaryField(null=True),
        ),
    ]
