# Generated by Django 5.0.3 on 2024-05-02 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_file_preview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="type",
            new_name="file_type",
        ),
    ]
