# Generated by Django 5.0.3 on 2024-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_rename_type_file_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="avatar",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
    ]
