# Generated by Django 5.0.3 on 2024-05-06 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_chat_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="avatar",
        ),
    ]
