# Generated by Django 5.0.3 on 2024-05-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_remove_chat_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatline",
            name="message_hash",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
